batchsize: 8
cutoff: 10.0
d_h: 256
d_in: 1
d_model: 128
d_o: 256
data_dir: ./data/adme/
dataset: VDss_Lombardo
decay: 0.0
device: cuda
dim_in: 2
drop: 0.2
emb_dim: 128
epoch: 100
frag_layer: 6
gnn_layer: 4
lr: 0.0001
mask_ratio: 0.1
mf_layer: 2
model: FusionMamba
n_layer: 2
num_workers: 8
pretrain_path: null
runseed: 68596
save_dir: ./result_regression/VDss_Lombardo/scaffold/VDss_Lombardo_42_0.0001_Jan28_20:10:48/
save_model: true
sch_layer: 6
seed: 42
split: scaffold
task_type: regression
use_cat_fusion: true
use_fg_embedding: true
use_fp: true
use_gnn: true
use_gpt_embedding: true
use_graph_mamba: true
w_task: 1.0
