name: geom2
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - brotli=1.2.0=hed03a55_1
  - brotli-bin=1.2.0=hb03c661_1
  - bzip2=1.0.8=hda65f42_8
  - ca-certificates=2026.1.4=hbd8a1cb_0
  - cairo=1.18.4=he90730b_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py311h724c32c_4
  - cycler=0.12.1=pyhcf101f3_2
  - cyrus-sasl=2.1.28=hd9c7081_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h7e30c49_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=hc364b38_1
  - fonttools=4.61.1=py311h3778330_0
  - freetype=2.14.1=ha770c72_0
  - freetype-py=2.3.0=pyhd8ed1ab_0
  - greenlet=3.3.1=py311h1ddb823_0
  - icu=78.2=h33c6efd_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_2
  - krb5=1.21.3=h659f571_0
  - lcms2=2.18=h0c24ade_0
  - ld_impl_linux-64=2.45=default_hbd61a6d_105
  - lerc=4.0.0=h0aef613_1
  - libblas=3.11.0=5_h4a7cf45_openblas
  - libboost=1.86.0=hd24cca6_5
  - libboost-python=1.86.0=py311h1d5f577_5
  - libbrotlicommon=1.2.0=hb03c661_1
  - libbrotlidec=1.2.0=hb03c661_1
  - libbrotlienc=1.2.0=hb03c661_1
  - libcblas=3.11.0=5_h0358290_openblas
  - libdeflate=1.25=h17f619e_0
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libexpat=2.7.3=hecca717_0
  - libffi=3.5.2=h3435931_0
  - libfreetype=2.14.1=ha770c72_0
  - libfreetype6=2.14.1=h73754d4_0
  - libgcc=15.2.0=he0feb66_16
  - libgcc-ng=15.2.0=h69a702a_16
  - libgfortran=15.2.0=h69a702a_16
  - libgfortran5=15.2.0=h68bc16d_16
  - libglib=2.86.3=h6548e54_0
  - libgomp=15.2.0=he0feb66_16
  - libiconv=1.18=h3b78370_2
  - libjpeg-turbo=3.1.2=hb03c661_0
  - liblapack=3.11.0=5_h47877c9_openblas
  - liblzma=5.8.2=hb03c661_0
  - liblzma-devel=5.8.2=hb03c661_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libopenblas=0.3.30=pthreads_h94d23a6_4
  - libpng=1.6.54=h421ea60_0
  - libpq=18.1=hb80d175_3
  - librdkit=2025.09.4=h3c5c181_0
  - libsqlite=3.51.2=hf4e2dac_0
  - libstdcxx=15.2.0=h934c35e_16
  - libstdcxx-ng=15.2.0=hdf11a46_16
  - libtiff=4.7.1=h9d88235_1
  - libuuid=2.41.3=h5347b49_0
  - libwebp-base=1.6.0=hd42ef1d_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - matplotlib-base=3.10.8=py311h0f3be63_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=h2d0b736_3
  - numpy=2.4.1=py311h2e04523_0
  - openjpeg=2.5.4=h55fea9a_0
  - openldap=2.6.10=he970967_0
  - openssl=3.6.0=h26f9b46_0
  - packaging=26.0=pyhcf101f3_0
  - pandas=3.0.0=py311h8032f78_0
  - pcre2=10.47=haa7fec5_0
  - pillow=12.1.0=py311hf88fc01_0
  - pip=25.3=pyh8b19718_0
  - pixman=0.46.4=h54a6638_1
  - pthread-stubs=0.4=hb9d3cd8_1002
  - pycairo=1.29.0=py311hc1a9592_0
  - pyparsing=3.3.2=pyhcf101f3_0
  - python=3.11.9=hb806964_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python_abi=3.11=8_cp311
  - qhull=2020.2=h434a139_5
  - rdkit=2025.09.4=py311h34e1bb8_0
  - readline=8.3=h853b02a_0
  - reportlab=4.4.9=py311h49ec1c0_0
  - rlpycairo=0.4.0=pyh6c17108_0
  - setuptools=80.10.1=pyh332efcf_0
  - six=1.17.0=pyhe01879c_1
  - sqlalchemy=2.0.46=py311haee01d2_1
  - tk=8.6.13=noxft_h366c992_103
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025c=hc9c84f9_1
  - unicodedata2=17.0.0=py311h49ec1c0_1
  - wheel=0.46.3=pyhd8ed1ab_0
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=hb03c661_1
  - xorg-libxdmcp=1.1.5=hb03c661_1
  - xorg-libxext=1.3.7=hb03c661_0
  - xorg-libxrender=0.9.12=hb9d3cd8_0
  - xz=5.8.2=ha02ee65_0
  - xz-gpl-tools=5.8.2=ha02ee65_0
  - xz-tools=5.8.2=hb03c661_0
  - zlib-ng=2.3.2=hceb46e0_1
  - zstd=1.5.7=hb78ec9c_6
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - ase==3.27.0
      - astor==0.8.1
      - attrs==25.4.0
      - certifi==2026.1.4
      - cloudpickle==3.1.2
      - colorama==0.4.6
      - dnspython==2.8.0
      - einops==0.8.2
      - filelock==3.10.0
      - frozenlist==1.8.0
      - fsspec==2025.12.0
      - future==1.0.0
      - hyperopt==0.1.2
      - idna==3.11
      - importlib==1.0.4
      - jinja2==3.1.6
      - joblib==1.5.3
      - json-tricks==3.17.3
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.7.1
      - networkx==3.6.1
      - nni==2.9
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nvtx-cu11==11.8.86
      - prettytable==3.17.0
      - propcache==0.4.1
      - protobuf==6.33.4
      - psutil==7.2.1
      - pymongo==4.16.0
      - pythonwebhdfs==0.2.3
      - pyyaml==6.0.3
      - requests==2.32.5
      - responses==0.25.8
      - schema==0.7.8
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - simplejson==3.20.2
      - sympy==1.13.1
      - tabulate==0.9.0
      - tensorboardx==2.6.4
      - threadpoolctl==3.6.0
      - torch==2.6.0+cu118
      - torch-cluster==1.6.3+pt26cu118
      - torch-geometric==2.7.0
      - torch-scatter==2.1.2+pt26cu118
      - torch-sparse==0.6.18+pt26cu118
      - torch-spline-conv==1.2.2+pt26cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - tqdm==4.67.1
      - triton==3.2.0
      - typeguard==2.13.0
      - urllib3==2.6.3
      - wcwidth==0.5.0
      - websockets==16.0
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: /home/qk/anaconda3/envs/geom2
