batchsize: 8
cutoff: 10.0
d_model: 256
data_dir: ./data/adme/
dataset: Pgp_Broccatelli
decay: 0.0
device: cuda
dim_in: 2
drop: 0.1
emb_dim: 256
epoch: 100
gnn_layer: 6
lr: 0.0001
model: FusionMamba
n_layer: 2
num_workers: 8
pretrain_path: null
runseed: 26356
save_model: true
sch_layer: 6
seed: 42
split: scaffold
task_type: classification
use_cat_fusion: true
use_fg_embedding: true
use_fp: true
use_gnn: true
use_gpt_embedding: true
use_graph_mamba: true
w_task: 1.0
